# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "simplecov-gem-adapter"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Edgar"]
  s.date = "2013-12-12"
  s.description = "For some reason, there's no adapter for a gem in SimpleCov, an excellent, simple Ruby 1.9 coverage tool. So this one defines one in about 8 lines of code."
  s.email = "michael.j.edgar@dartmouth.edu"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/simplecov-gem-adapter.rb",
    "simplecov-gem-adapter.gemspec"
  ]
  s.homepage = "http://github.com/michaeledgar/simplecov-gem-adapter"
  s.require_paths = ["lib"]
  s.rubyforge_project = "simplecov-gem-adapter"
  s.rubygems_version = "2.0.3"
  s.summary = "SimpleCov adapter for a standard Ruby Gem."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<simplecov>, [">= 0.8.1"])
    else
      s.add_dependency(%q<simplecov>, [">= 0.8.1"])
    end
  else
    s.add_dependency(%q<simplecov>, [">= 0.8.1"])
  end
end

